version: '3.1'
x-database-variables: &database-variables
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/schedule_db?createDatabaseIfNotExist=true
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root

services:
  db:
    image: mysql:5.6
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  luizalabs-communication-api:
    image: cadulox/luizalabs-communication-api:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      <<: *database-variables
    depends_on:
      - db

volumes:
  mysql-data: